### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Danilwsk** [GamerMJay/BetterRepair#1]
Add a description to config.yml so I can change the description.

**Comment by Danilwsk** [comment]
It gives me an error

**Comment by Danilwsk** [comment]
thank you for adding description
But github writes that 4 problems have been found

**Comment by Danilwsk** [comment]
When entering the command crashes

**Comment by GamerMJay** [comment]
I'm fixing pls wait...

**Comment by Danilwsk** [comment]
Okay I'll wait

**Comment by Danilwsk** [comment]
InInIn In gIn giIn gitIn gitsIn gIn github 4 problems you write with this plugin

**Comment by Danilwsk** [comment]
In github, you have 4 problems in this plugin

**Comment by GamerMJay** [comment]
I know!

**Comment by GamerMJay** [comment]
Hey @Danilwsk Repair is finish :)
