### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DimonYoing** [GamerMJay/BetterRepair#2]
Fix the plugin , it doesn't work

**Comment by GamerMJay** [comment]
send the error

**Comment by DimonYoing** [comment]
I can't send an error, because when I try to fix an item, it crashes from the server and writes "server closed"

**Comment by DimonYoing** [comment]
?

**Comment by GamerMJay** [comment]
![Uploading Screenshot_2022-02-03-21-34-17-89_5c8300b655012b1930f2e0a7b81bf6a9.jpg…]()

So it works for me
