### ISSUE TITLE
Issue config.yml

### ISSUE THREAD

**Issue by NeturCrafter** [GamerMJay/BetterRepair#5]
Hey, @GamerMJay 
You should rename **instanceof** to  instaceof in your Config.yml as this is also specified in the repair.php file.

**Comment by GamerMJay** [comment]
hey what do you mean exactly? Do you mean that I should change the name where you can't repair the items?

**Comment by NetureCrafter** [comment]
repair.php:
$player->sendMessage($config->get("**instaceof**"));

config.yml:
**instanceof**: ""

**Comment by GamerMJay** [comment]
No problem
